### ISSUE TITLE
Update to 1.21?

### ISSUE THREAD

**Issue by bbfh-dev** [shurik204/codebridge#1]
Would really appreciate support for 1.21, since 1.20.6 is a minor release. 😄

**Comment by shurik204** [comment]
There've been a few rendering changes in 1.21 that I'm figuring out right now. I saw your message in the Better Highlighting thread lol. That mod will be next btw.

**Comment by shurik204** [comment]
Oh, wait. I just realised what repository this is. 😳
This mod doesn't even have a public release.

**Comment by shurik204** [comment]
I've updated my mods to 1.21. Including this one.

https://github.com/shurik204/codebridge/releases/tag/0.1.1
